[auth]
verifyUrl="http://localhost:8080/auth/api/auth/verify"

[http]
port=44100
publicUrl="http://localhost:8080/sponsor"

[mongo]
url="mongodb://localhost:27017/sponsor-development"

[mqtt]
url="mqtt://localhost/"